backend:
  name: github
  repo: USERNAME/REPO
  branch: main

media_folder: "Assets"
public_folder: "/Assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.json"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }