backend:
  name: git-gateway
  repo: ahmedtamer-20cm/Subjects-Online
  branch: main

media_folder: "Assets"
public_folder: "/Assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.json"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
- name: "subjects"
    label: "المواد الدراسية"
    folder: "../subjects"
    filter: {field: "title", value: ""} # هيفلتر لو فيه ملفات زيادة
    extension: "html" # عشان يقرأ ملفات الـ index.html
    format: "frontmatter" # بيحاول يقرأ البيانات اللي فوق في الملف
    create: true
    nested:
      depth: 10 # دي أهم خطوة عشان يدخل جوه الفولدراتaccounting و chapters
    fields:
      - { label: "اسم الفصل/الدرس", name: "title", widget: "string" }
      - { label: "المحتوى", name: "body", widget: "markdown" }